name: 'run-ghost-inspector-suite'
description: 'Runs a single ghost inspector suite and resolves based on test results (including screenshots)'
inputs:
  startURL:
    description: 'optional startURL for the test suite'
    required: false
    default: ''
  suiteID:
    description: 'ghost inspector suiteID'
    required: true
    default: 'UNDEFINED'
  GHOST_INSPECTOR_API_KEY:
    description: 'ghost inspector API Key'
    required: true
    default: 'UNDEFINED'

runs:
  using: 'node12'
  main: 'index.js'